apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

images:
  - name: git.private.rjbhome.net/rjb/chat-bdc
    newTag: latest
  - name: git.private.rjbhome.net/rjb/chat-bdc-deploy
    newTag: latest
